site_name: MetaTrader-Panel
site_url: https://metatrader-panel.com/en/
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../generated/en'
use_directory_urls: false

theme:
  #custom_dir: overrides
  auto_themed: true
  language: en
  name: material
  favicon: images/FM32.ico
  logo: images/FM32.ico 
  palette:
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    #- navigation.indexes #important!
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.follow
    - toc.integrate 

copyright: Copyright &copy; 1996 - 2025 Profundus Drusus

markdown_extensions:
  - attr_list

plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: false
       shadow: true
       
   - search:

extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:<info@metatrader-panel.com>
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de       

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
extra_css:
  - stylesheets/extra.css
  
nav:
  - Home: 
    - Overview: index.md
  - Features: 
    - Tick Chart: features/tick-chart.md
    - Position Properties: features/position-props.md      
  - How it works:
    - Set up in 3 steps: signup/set-up-in-3-steps.md
    - Auth0: signup/auth0.md
  - FAQ:
    - Stop questions: faq/stops.md
    - Tick chart questions: faq/tick-chart.md     
  - Download:
    - Latest version: download/download.md  
  - About:
    - Release Notes: about/release-notes.md
    - License: about/license.md    