site_name: MetaTrader-Panel
site_url: https://metatrader-panel.com/en/
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../generated/en'
#use_directory_urls: false

theme:
  icon: assets/LogoFullset.ico
  annotation: material/plus-circle 
  custom_dir: overrides
  auto_themed: true
  language: en
  name: material
  favicon: images/LogoFullset.ico
  logo: images/LogoFullset.ico 
  palette:
    #- scheme: slate
      #primary: blue
      #accent: light blue
      #toggle:
        #icon: material/toggle-switch
        #name: Switch to light mode
    - scheme: custom
      #primary: blue
      #accent: blue
      #toggle:
        #icon: material/toggle-switch-off-outline
        #name: Switch to dark mode
  features:
    - search.suggest
    - navigation.tracking
    - search.highlight
    #- navigation.indexes #important!
    #- navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    #- navigation.path
    - navigation.top
    - toc.follow
    #- toc.integrate 


plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: false
       shadow: true
   - search:
       lang: en
extra:
  footer_links:
    - text: "Privacy policy"
      href: "https://doc.metatrader-panel.com/en/legal/privacy-policy"
    - text: "Imprint"
      href: "https://doc.metatrader-panel.com/dee/legal/imprint"
  generator: false
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de  
     

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
extra_css:
  - stylesheets/extra.css
  - stylesheets/style.css
  - stylesheets/namari-color.css
  - stylesheets/animate.css
  - stylesheets/font-awesome.min.css
  - stylesheets/cookieconsent.css
  
extra_javascript:
  - javascript/jquery.1.8.3.min.js
  - javascript/wow.min.js
  #- javascript/jquery.enllax.js
  - javascript/jquery.easing.min.js
  - javascript/jquery.waypoints.min.js
  - javascript/site.js
  - javascript/featherlight.min.js
  - javascript/featherlight.gallery.min.js
  - javascript/images-loaded.min.js
  - javascript/lightbox.min.js
  - javascript/change-text.js
  - javascript/cookieconsent-config.js
    
nav:
  - Home: 
    - Overview: index.md
  - Modules: 
    - Tick Chart: features/tick-chart.md
    - Position Properties: features/position-props.md      
  - How it works:
    - Set up in 3 steps: signup/set-up-in-3-steps.md
    - Auth0: signup/auth0.md
  - FAQ:
    - Overview: faq/index.md
    - Common: faq/common-faq.md
    - Interface: faq/panel-faq.md
    - Auth0: faq/auth0-faq.md
    - Fibonacci: faq/fibonacci-faq.md
    - Orders: faq/order-faq.md    
    - Profit & Loss: faq/pl-faq.md    
    - Stops: faq/stops-faq.md 
    - Tick Chart: faq/tick-chart-faq.md   
  - Download:
    - Latest version: download/download.md 
  - Pricing:
    - Order: https://doc.metatrader-panel.com/en/#pricing
  - More:
    - Jobs: misc/job-offers.md
    - Privacy Policy: legal/privacy-policy.md
    - Imprint: legal/imprint.md   