site_name: MetaTrader-Panel
site_url: https://metatrader-panel.com/de/
docs_dir: '../../docs/de'                           # Where to find the English markdown files
site_dir: '../../generated/de'
#use_directory_urls: false

theme:
  custom_dir: overrides
  auto_themed: true
  language: de
  name: material
  favicon: images/FM32.ico
  logo: images/FM32.ico 
  palette:
    #- scheme: slate
      #primary: blue
      #accent: light blue
      #toggle:
        #icon: material/toggle-switch
        #name: Switch to light mode
    - scheme: custom
      #primary: blue
      #accent: blue
      #toggle:
        #icon: material/toggle-switch-off-outline
        #name: Switch to dark mode
  features:
    - search.suggest
    - navigation.tracking
    - search.highlight
    - navigation.indexes #important!
    #- navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - toc.follow
    #- toc.integrate 

copyright: Copyright &copy; 1996 - 2025 Profundus Drusus Maior

plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: false
       shadow: true
   - search:
       lang: de
extra:
  footer_links:
    - text: "Datenschutz"
      href: "https://doc.metatrader-panel.com/de/legal/privacy-policy"
    - text: "Impressum"
      href: "https://doc.metatrader-panel.com/de/legal/imprint"
  generator: false
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de       

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
extra_css:
  - stylesheets/extra.css
  - stylesheets/style.css
  - stylesheets/namari-color.css
  - stylesheets/animate.css
  - stylesheets/font-awesome.min.css
  - stylesheets/cookieconsent.css
  
extra_javascript:
  - javascript/jquery.1.8.3.min.js
  - javascript/wow.min.js
  #- javascript/jquery.enllax.js
  - javascript/jquery.easing.min.js
  - javascript/jquery.waypoints.min.js
  - javascript/site.js
  - javascript/featherlight.min.js
  - javascript/featherlight.gallery.min.js
  - javascript/images-loaded.min.js
  - javascript/lightbox.min.js
  - javascript/change-text.js
  - javascript/cookieconsent-config.js
  
nav:
  - Home: 
    - Übersicht: index.md
  - Features: 
    - Übersicht: features/index.md
    - Fibonacci: features/fibonacci.md
    - Tick Chart: features/tick-chart.md
    - Position Properties: features/position-props.md      
  - So funktiert es:
    - Set up in 3 steps: signup/set-up-in-3-steps.md
    - Auth0: signup/auth0.md
  - FAQ:
    - Übersicht: faq/index.md
    - Allgemein: faq/common-faq.md
    - Auth0: faq/auth0-faq.md
    - Fibonacci: faq/fibonacci-faq.md
    - Orders: faq/order-faq.md    
    - Stops: faq/stops-faq.md    
    - Trade Panel: faq/panel-faq.md
    - Tick Chart: faq/tick-chart-faq.md  


    - Profit & Loss: faq/pl-faq.md
  - Download:
    - Latest version: download/download.md 
  - Preise:
    - Order: https://doc.metatrader-panel.com/de/#go-pricing
  - FollowMe: https://client.metatrader-panel.com/
  - Mehr:
    - Jobs: misc/job-offers.md
    - Datenschutz: legal/privacy-policy.md
    - Impressum: legal/imprint.md   